name: Deploy to aks

on:
  workflow_call:
    inputs:
      deploy-to:
        required: true
        type: string
      cluster-name:
        required: true
        type: string
      resource-group:
        required: true
        type: string
      replicas:
        required: true
        type: string
        default: '1'
    secrets:
      azure-credentials:
        required: true
jobs:
  deploy:
    name: Deploy to ${{ inputs.deploy-to }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set image version by tag
      run: echo "IMAGE_VERSION=$GITHUB_REF_NAME" >> $GITHUB_ENV
      if: github.ref.type == 'tag'
    - name: Set image version by property
      run: echo "IMAGE_VERSION=$(grep "^version=" gradle.properties | cut -d'=' -f2 | tr -d '[:space:]')" >> $GITHUB_ENV
      if: github.ref.type != 'tag'
    - name: update replicas
      run: |
        sed -i 's/@replicas@/${{ inputs.replicas }}/g' k8s.yaml
        sed -i 's/@version@/$IMAGE_VERSION/g' k8s.yaml

    # Set the target Azure Kubernetes Service (AKS) cluster.
    - uses: azure/aks-set-context@v2.0
      with:
        creds: '${{ secrets.azure-credentials }}'
        cluster-name: ${{ inputs.cluster-name }}
        resource-group: ${{ inputs.resource-group }}
      # Deploy app to AKS
    - uses: Azure/k8s-deploy@v1
      with:
        manifests: k8s.yaml
