name: Gradle build test and sonar scan

on:
  workflow_call:
    secrets:
      external-maven-repo-password:
        required: true
jobs:
  build:
    name: Gradle build, test and publish
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        cache: 'gradle'
    - name: Debug
      run: |
       echo '${{ toJson(github) }}' > githubcontext.json
       cat githubcontext.json
    - name: Set package version by tag
      run: echo "PACKAGE_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
      if: github.ref_type == 'tag'
    - name: Set package version by property
      run: echo "PACKAGE_VERSION=$(grep "^version=" gradle.properties | cut -d'=' -f2 | tr -d '[:space:]')" >> $GITHUB_ENV
      if: github.ref_type != 'tag'
    - name: Set gradlew executalbe
      run: chmod +x gradlew
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v3
      env:
        GITHUB_CI: "true"
      with:
        arguments: |
          build  
          publish -Pversion=${{ env.PACKAGE_VERSION }}
          -PexternalPassword=${{ secrets.external-maven-repo-password }}
