name: Gradle build test and sonar scan

on:
  workflow_call:
    secrets:
      external-maven-repo-password:
        required: true
      sonar-token:
        required: true
      githubToken:
        required: true
      snyk-token:
        required: false
jobs:
  build:
    name: Gradle build, test and sonar scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: read
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        cache: 'gradle'
    - name: Set gradlew executalbe
      run: chmod +x gradlew
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.sonar-token }}
        SONAR_HOST_URL: https://sonarcloud.io
        GITHUB_TOKEN: ${{ secrets.githubToken }}
      with:
        arguments: build sonarqube -PexternalPassword=${{ secrets.external-maven-repo-password }}
    - name: Upload test report if build failed
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: build-reports
        path: '**/build/reports/**/*'
        retention-days: 5
  checkSecrets:
    runs-on: ubuntu-latest
    outputs:
      HAS_SNYK_TOKEN: ${{ steps.check.outputs.SNYK_TOKEN }}
    steps:
      - run: >
          echo "::set-output name=SNYK_TOKEN::${{ env.SNYK_TOKEN != '' }}";
        id: check
        env:
          SNYK_TOKEN: ${{ secrets.snyk-token }}
  snykScan:
    name: Snyk scan using gradle
    if: >
      needs.checkSecrets.outputs.HAS_SNYK_TOKEN == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: checkSecrets
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set gradlew executalbe
      run: chmod +x gradlew
    - name: Run Snyk to monitor for vulnerabilities
      uses: snyk/actions/gradle-jdk17@master
      env:
        SNYK_TOKEN: ${{ secrets.snyk-token }}
        ORG_GRADLE_PROJECT_externalPassword: ${{ secrets.external-maven-repo-password }}
      with:
        args: --all-sub-projects  --remote-repo-url=${{ server_url }}/${{ github.repository }}
        command: monitor